/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaGUI;

import capaGUI.GestionProductos.ConexionSQLite;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author vizcacha
 */
public class Crear_Cuenta extends javax.swing.JPanel {

    /**
     * Creates new form Crear_Cuenta
     */
    public Crear_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_NUsuario = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        Password_contraseña = new javax.swing.JPasswordField();
        Button_CrearCuenta = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("DNI");

        jLabel3.setText("Correo");

        jLabel4.setText("Nombre de Usuario");

        jLabel5.setText("Contraseña");

        Button_CrearCuenta.setText("Crear Cuenta");
        Button_CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_CrearCuenta)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Password_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txt_NUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_NUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Password_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Button_CrearCuenta)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        Button_CrearCuenta.getAccessibleContext().setAccessibleName("Crear Cuenta");
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearCuentaActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText().trim();
        String dni = txt_DNI.getText().trim();
        String correo = txt_correo.getText().trim();
        if (!correo.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo electrónico válido", "Correo inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String usuario = txt_NUsuario.getText().trim();
        char[] claveChars = Password_contraseña.getPassword();
        String claveHash = hashContraseña(claveChars);
        String tipo = "cliente";

        // Validación básica
        if (nombre.isEmpty() || dni.isEmpty() || claveHash.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sqlVerificar = "SELECT COUNT(*) FROM personas WHERE correo = ? OR usuario = ?";
        String sqlInsertar = "INSERT INTO personas (nombre, dni, tipo, correo, usuario, clave) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = ConexionSQLite.conectar();
             PreparedStatement stmtVerificar = conn.prepareStatement(sqlVerificar);
             PreparedStatement stmtInsertar = conn.prepareStatement(sqlInsertar)) {

            // Verificar si ya existe correo o usuario
            stmtVerificar.setString(1, correo);
            stmtVerificar.setString(2, usuario);
            ResultSet rs = stmtVerificar.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Correo o nombre de usuario ya registrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Insertar nuevo usuario
            stmtInsertar.setString(1, nombre);
            stmtInsertar.setString(2, dni);
            stmtInsertar.setString(3, tipo);
            stmtInsertar.setString(4, correo);
            stmtInsertar.setString(5, usuario);
            stmtInsertar.setString(6, claveHash);

            stmtInsertar.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            
            
            JFrame ventana = (JFrame) SwingUtilities.getWindowAncestor(this);

            // Asegúrate que el JFrame tenga un JPanel llamado 'content'
            JPanel content = (JPanel) ventana.getContentPane().getComponent(0); // o usa ventana.content si es público

            content.removeAll(); // Limpiar el contenido anterior
            content.add(new Inicia_Sesion()); // Agregar el nuevo panel
            content.revalidate();
            content.repaint();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al crear cuenta:\n" + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_CrearCuentaActionPerformed

    
    public static String hashContraseña(char[] contraseña) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashBytes = md.digest(new String(contraseña).getBytes(StandardCharsets.UTF_8));
        StringBuilder sb = new StringBuilder();
        for (byte b : hashBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException("Error al hacer hash de la contraseña", e);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CrearCuenta;
    private javax.swing.JPasswordField Password_contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_NUsuario;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
