/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGUI;

import capaDatos.Persona;
import capaLogica.ControladoraLogica;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author lizan
 */
public class MenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        content.setLayout(new BorderLayout());
        btn_GestionarProductos.setVisible(false);
        btn_HistoriaDeVentas.setVisible(false);
        btn_RealizarVenta.setVisible(false);
    }
    public void cambiarPanel(JPanel nuevoPanel) {
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(nuevoPanel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_CrearCuenta = new javax.swing.JButton();
        Button_InicioSesion1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_GestionarProductos = new javax.swing.JButton();
        btn_RealizarVenta = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_HistoriaDeVentas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(204, 204, 204));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setText("Sistema de Botica MarlenyFarma");

        Button_CrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_CrearCuenta.setText("Crear una Cuenta");
        Button_CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearCuentaActionPerformed(evt);
            }
        });

        Button_InicioSesion1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_InicioSesion1.setText("Inicia Sesión");
        Button_InicioSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_InicioSesion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(Button_InicioSesion1)
                        .addGap(115, 115, 115)
                        .addComponent(Button_CrearCuenta)
                        .addGap(172, 172, 172))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(212, 212, 212)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CrearCuenta)
                    .addComponent(Button_InicioSesion1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setAutoscrolls(true);

        btn_GestionarProductos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btn_GestionarProductos.setText("GESTIONAR PRODUCTOS");
        btn_GestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GestionarProductosActionPerformed(evt);
            }
        });

        btn_RealizarVenta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btn_RealizarVenta.setText("REALIZAR VENTA");
        btn_RealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarVentaActionPerformed(evt);
            }
        });

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_HistoriaDeVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_HistoriaDeVentas.setText("HISTORIAL DE VENTAS");
        btn_HistoriaDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HistoriaDeVentasActionPerformed(evt);
            }
        });

        jButton4.setText("BACKUP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_GestionarProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(btn_HistoriaDeVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_RealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btn_GestionarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_RealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_HistoriaDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GestionarProductosActionPerformed
        // TODO add your handling code here:
        
        GestionProductos gProductos = new GestionProductos();
        gProductos.setSize(1161, 808);
        gProductos.setLocation(0, 0);
        
        content.removeAll();
        content.add(gProductos);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_GestionarProductosActionPerformed

    private void btn_RealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarVentaActionPerformed
        // TODO add your handling code here:
        
        PuntoDeVenta pVenta= new PuntoDeVenta();
        pVenta.setSize(1161, 808);
        pVenta.setLocation(0, 0);
        
        content.removeAll();
        content.add(pVenta);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_RealizarVentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_HistoriaDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HistoriaDeVentasActionPerformed
        // TODO add your handling code here:
       Historial_venta pVenta= new Historial_venta();
        pVenta.setSize(1161, 808);
        pVenta.setLocation(0, 0);
        
        content.removeAll();
        content.add(pVenta);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_HistoriaDeVentasActionPerformed

    private void Button_InicioSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_InicioSesion1ActionPerformed
        // TODO add your handling code here:
         Inicia_Sesion pVenta= new Inicia_Sesion();
        pVenta.setSize(1161, 808);
        pVenta.setLocation(0, 0);
        
        content.removeAll();
        content.add(pVenta);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_Button_InicioSesion1ActionPerformed

    private void Button_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearCuentaActionPerformed
        // TODO add your handling code here:
        Crear_Cuenta pVenta= new Crear_Cuenta();
        pVenta.setSize(1161, 808);
        pVenta.setLocation(0, 0);
        
        content.removeAll();
        content.add(pVenta);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_Button_CrearCuentaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ControladoraLogica.BackupSQLite();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    private Persona usuarioActual;

    public void setUsuarioActual(Persona persona) {
        this.usuarioActual = persona;
    }

    public Persona getUsuarioActual() {
        return usuarioActual;
    }
    public void actualizarInterfazPorRol() {
        if (usuarioActual == null) return;

        boolean esVendedor = usuarioActual.getTipo().equalsIgnoreCase("vendedor");
        boolean esAdmin = usuarioActual.getTipo().equalsIgnoreCase("admin");


        // Desactiva o esconde los botones restringidos para clientes
        btn_GestionarProductos.setVisible(esAdmin || esVendedor);
        btn_HistoriaDeVentas.setVisible(esAdmin);
        btn_RealizarVenta.setVisible(esVendedor || esAdmin);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CrearCuenta;
    private javax.swing.JButton Button_InicioSesion1;
    private javax.swing.JButton btn_GestionarProductos;
    private javax.swing.JButton btn_HistoriaDeVentas;
    private javax.swing.JButton btn_RealizarVenta;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
